### ISSUE TITLE
не понятно, как высвобождаются ресурсы тикера, нет вызова Stop 

### ISSUE THREAD

**Issue by webngt** [ebrvkv/intasks#1]
https://github.com/ebrvkv/intasks/blob/8d87975525771cd768c870de2b3034ce2c42eece/cmd/requests/main.go#L35

**Comment by webngt** [comment]
Контрольный вопрос - как это можно быстро исправить, не меняя радикально структуру кода.

**Comment by ebrvkv** [comment]
Так как Tick не закрывает рутины тикера, добавлен t.Stop() перед циклом.
